version: '2'
services:
  frontend:
    container_name: aqua_frontend
    build:
      context: .
      dockerfile: docker/dev/frontend/Dockerfile
    tty: true
    volumes:
      - ./frontend:/usr/src/app
    ports:
    - 3000:3000
  backend:
    container_name: aqua_backend_dev
    build:
      context: .
      dockerfile: ./docker/dev/backend/Dockerfile
    volumes:
      - ./backend:/usr/src/app
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - 8000:8000
    environment:
      TZ: "Europe/Berlin"