version: '2'
services:
  #  frontend:
  #    container_name: aqua_frontend
  #    build:
  #      context: .
  #      dockerfile: docker/prod/frontend/Dockerfile
  #    volumes:
  #      - ./frontend:/usr/src/app
  backend:
    container_name: aqua_backend
    restart: always
    build:
      context: .
      dockerfile: ./docker/prod/backend/Dockerfile
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - 8000:8000